// <auto-generated />
using System;
using AutoTaller.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoTaller.Infrastructure.Migrations
{
    [DbContext(typeof(AutoTallerDbContext))]
    [Migration("20251008213222_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutoTaller.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("json");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("json");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan.perez@email.com",
                            FechaRegistro = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan Pérez",
                            Telefono = "3001234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.lopez@email.com",
                            FechaRegistro = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María López",
                            Telefono = "3009876543"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos.rodriguez@email.com",
                            FechaRegistro = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos Rodríguez",
                            Telefono = "3005551234"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ana.martinez@email.com",
                            FechaRegistro = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana Martínez",
                            Telefono = "3007778888"
                        },
                        new
                        {
                            Id = 5,
                            Email = "luis.hernandez@email.com",
                            FechaRegistro = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis Hernández",
                            Telefono = "3003334444"
                        },
                        new
                        {
                            Id = 6,
                            Email = "carmen.silva@email.com",
                            FechaRegistro = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carmen Silva",
                            Telefono = "3006665555"
                        },
                        new
                        {
                            Id = 7,
                            Email = "roberto.diaz@email.com",
                            FechaRegistro = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Roberto Díaz",
                            Telefono = "3002223333"
                        },
                        new
                        {
                            Id = 8,
                            Email = "patricia.ruiz@email.com",
                            FechaRegistro = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Patricia Ruiz",
                            Telefono = "3008889999"
                        },
                        new
                        {
                            Id = 9,
                            Email = "jorge.castro@email.com",
                            FechaRegistro = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Jorge Castro",
                            Telefono = "3004445555"
                        },
                        new
                        {
                            Id = 10,
                            Email = "sofia.morales@email.com",
                            FechaRegistro = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sofía Morales",
                            Telefono = "3001112222"
                        });
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.DetalleOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenServicioId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("DetallesOrden", (string)null);
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<decimal>("ManoObra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalRepuestos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("OrdenServicioId")
                        .IsUnique();

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.OrdenServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaEstimada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<decimal>("ManoObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("MecanicoId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MecanicoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("OrdenesServicio", (string)null);
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Repuestos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "FIL-001",
                            Descripcion = "Filtro de Aceite",
                            PrecioUnitario = 15000m,
                            Stock = 50,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "FIL-002",
                            Descripcion = "Filtro de Aire",
                            PrecioUnitario = 25000m,
                            Stock = 40,
                            StockMinimo = 8
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "FIL-003",
                            Descripcion = "Filtro de Combustible",
                            PrecioUnitario = 30000m,
                            Stock = 35,
                            StockMinimo = 7
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "BUJ-001",
                            Descripcion = "Bujías (set 4)",
                            PrecioUnitario = 45000m,
                            Stock = 30,
                            StockMinimo = 6
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "PAST-001",
                            Descripcion = "Pastillas de Freno Delanteras",
                            PrecioUnitario = 80000m,
                            Stock = 25,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "PAST-002",
                            Descripcion = "Pastillas de Freno Traseras",
                            PrecioUnitario = 70000m,
                            Stock = 25,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "DISCO-001",
                            Descripcion = "Discos de Freno Delanteros (par)",
                            PrecioUnitario = 150000m,
                            Stock = 20,
                            StockMinimo = 4
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "ACEIT-001",
                            Descripcion = "Aceite Sintético 5W30 (garrafa)",
                            PrecioUnitario = 85000m,
                            Stock = 60,
                            StockMinimo = 15
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "ACEIT-002",
                            Descripcion = "Aceite Mineral 20W50 (garrafa)",
                            PrecioUnitario = 55000m,
                            Stock = 45,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "BANDA-001",
                            Descripcion = "Banda de Distribución",
                            PrecioUnitario = 120000m,
                            Stock = 18,
                            StockMinimo = 4
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "CORREA-001",
                            Descripcion = "Correa de Accesorios",
                            PrecioUnitario = 35000m,
                            Stock = 22,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "BAT-001",
                            Descripcion = "Batería 12V 45Ah",
                            PrecioUnitario = 280000m,
                            Stock = 15,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "LIQ-001",
                            Descripcion = "Líquido Refrigerante (1L)",
                            PrecioUnitario = 18000m,
                            Stock = 50,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "LIQ-002",
                            Descripcion = "Líquido de Frenos (500ml)",
                            PrecioUnitario = 22000m,
                            Stock = 40,
                            StockMinimo = 8
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "LLANTA-001",
                            Descripcion = "Llanta 185/65 R15",
                            PrecioUnitario = 250000m,
                            Stock = 16,
                            StockMinimo = 4
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "AMOR-001",
                            Descripcion = "Amortiguador Delantero",
                            PrecioUnitario = 180000m,
                            Stock = 12,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "AMOR-002",
                            Descripcion = "Amortiguador Trasero",
                            PrecioUnitario = 160000m,
                            Stock = 12,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "TERM-001",
                            Descripcion = "Termostato",
                            PrecioUnitario = 45000m,
                            Stock = 20,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "BOMBA-001",
                            Descripcion = "Bomba de Agua",
                            PrecioUnitario = 95000m,
                            Stock = 10,
                            StockMinimo = 2
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "EMBRAGUE-001",
                            Descripcion = "Kit de Embrague",
                            PrecioUnitario = 350000m,
                            Stock = 8,
                            StockMinimo = 2
                        });
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@autotaller.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Admin Principal",
                            PasswordHash = "$2a$11$6p3L0hKfxJ8vQ9xMzN3YPO3L8hKfxJ8vQ9xMzN3",
                            Rol = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "mecanico1@autotaller.com",
                            FechaCreacion = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos Méndez",
                            PasswordHash = "$2a$11$6p3L0hKfxJ8vQ9xMzN3YPO3L8hKfxJ8vQ9xMzN3",
                            Rol = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "mecanico2@autotaller.com",
                            FechaCreacion = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura Gómez",
                            PasswordHash = "$2a$11$6p3L0hKfxJ8vQ9xMzN3YPO3L8hKfxJ8vQ9xMzN3",
                            Rol = 2
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Email = "recepcion1@autotaller.com",
                            FechaCreacion = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana Torres",
                            PasswordHash = "$2a$11$6p3L0hKfxJ8vQ9xMzN3YPO3L8hKfxJ8vQ9xMzN3",
                            Rol = 3
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Email = "recepcion2@autotaller.com",
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro Ramírez",
                            PasswordHash = "$2a$11$6p3L0hKfxJ8vQ9xMzN3YPO3L8hKfxJ8vQ9xMzN3",
                            Rol = 3
                        });
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Kilometraje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehiculos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2020,
                            ClienteId = 1,
                            Kilometraje = 45000,
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            VIN = "1HGBH41JXMN109186"
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2019,
                            ClienteId = 1,
                            Kilometraje = 52000,
                            Marca = "Honda",
                            Modelo = "Civic",
                            VIN = "2HGFC2F59HH123456"
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2021,
                            ClienteId = 2,
                            Kilometraje = 30000,
                            Marca = "Chevrolet",
                            Modelo = "Spark",
                            VIN = "3GCPKSE78HG234567"
                        },
                        new
                        {
                            Id = 4,
                            Anio = 2020,
                            ClienteId = 3,
                            Kilometraje = 40000,
                            Marca = "Mazda",
                            Modelo = "3",
                            VIN = "4M2CU87198J345678"
                        },
                        new
                        {
                            Id = 5,
                            Anio = 2018,
                            ClienteId = 3,
                            Kilometraje = 75000,
                            Marca = "Nissan",
                            Modelo = "Sentra",
                            VIN = "5N1DR2MM8FC456789"
                        },
                        new
                        {
                            Id = 6,
                            Anio = 2022,
                            ClienteId = 4,
                            Kilometraje = 15000,
                            Marca = "Hyundai",
                            Modelo = "Accent",
                            VIN = "6KMHM81BXMU567890"
                        },
                        new
                        {
                            Id = 7,
                            Anio = 2021,
                            ClienteId = 5,
                            Kilometraje = 25000,
                            Marca = "Kia",
                            Modelo = "Rio",
                            VIN = "7KNDJ23C08K678901"
                        },
                        new
                        {
                            Id = 8,
                            Anio = 2019,
                            ClienteId = 6,
                            Kilometraje = 60000,
                            Marca = "Renault",
                            Modelo = "Logan",
                            VIN = "8LRBG0RB0KN789012"
                        },
                        new
                        {
                            Id = 9,
                            Anio = 2020,
                            ClienteId = 7,
                            Kilometraje = 48000,
                            Marca = "Volkswagen",
                            Modelo = "Gol",
                            VIN = "9WVWZZZ1KZW890123"
                        },
                        new
                        {
                            Id = 10,
                            Anio = 2021,
                            ClienteId = 8,
                            Kilometraje = 32000,
                            Marca = "Ford",
                            Modelo = "Fiesta",
                            VIN = "1FADP3K28JL901234"
                        },
                        new
                        {
                            Id = 11,
                            Anio = 2020,
                            ClienteId = 9,
                            Kilometraje = 38000,
                            Marca = "Suzuki",
                            Modelo = "Swift",
                            VIN = "2SUZUKI96MN012345"
                        },
                        new
                        {
                            Id = 12,
                            Anio = 2019,
                            ClienteId = 10,
                            Kilometraje = 55000,
                            Marca = "Mitsubishi",
                            Modelo = "Mirage",
                            VIN = "3MIAGE92LK123456"
                        });
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.DetalleOrden", b =>
                {
                    b.HasOne("AutoTaller.Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany("DetallesOrden")
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTaller.Domain.Entities.Repuesto", "Repuesto")
                        .WithMany("DetallesOrden")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenServicio");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Factura", b =>
                {
                    b.HasOne("AutoTaller.Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithOne("Factura")
                        .HasForeignKey("AutoTaller.Domain.Entities.Factura", "OrdenServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.OrdenServicio", b =>
                {
                    b.HasOne("AutoTaller.Domain.Entities.Usuario", "Mecanico")
                        .WithMany("OrdenesAsignadas")
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTaller.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mecanico");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("AutoTaller.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.OrdenServicio", b =>
                {
                    b.Navigation("DetallesOrden");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Repuesto", b =>
                {
                    b.Navigation("DetallesOrden");
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("OrdenesAsignadas");
                });

            modelBuilder.Entity("AutoTaller.Domain.Entities.Vehiculo", b =>
                {
                    b.Navigation("OrdenesServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
